### PR TITLE
Update SOCIS Information

### PR DESCRIPTION
**Pull request by thealphadollar**
The PR brings in the following updates to the list:

- SOCIS, unlike previous versions, now accepts students of all nationalities and provides a stipend for everyone.

- Add the timeline for SOCIS.

References:
1.  Third FAQ from the top: https://socis.esa.int/frequently-asked-questions/

### CODE REVIEW

**Comment by thealphadollar** [comment]
> I see you have added an IIT SoC, delete. I have been closing universities' SoC PRs. I am opening one ticket, you can ref/use it and separately add, I can just add universities' SoCs as well. I think it would be nice having everything in the list.
> 
> Please squash the commits.

@tapaswenipathak I would humbly request you to please squash and merge while merging the PR as I'm maintaining another repository and I need to have commits separately there.

**Comment by tapaswenipathak** [comment]
On Wed, 8 May 2019, 8:42 p.m. Shivam Kumar Jha, <notifications@github.com>
wrote:

> I see you have added an IIT SoC, delete. I have been closing universities'
> SoC PRs. I am opening one ticket, you can ref/use it and separately add, I
> can just add universities' SoCs as well. I think it would be nice having
> everything in the list.
>
> Please squash the commits.
>
> @tapaswenipathak <https://github.com/tapaswenipathak> I would humbly
> request you to please squash and merge while merging the PR as I'm
> maintaining another repository and I need to have commits separately there.
>
Please read the comment properly. I can do squash and merge, not a problem.

**Comment by thealphadollar** [comment]
@tapaswenipathak Sorry for the misunderstanding; I've reverted my PR adding SoI. 

Is the Pull Request good to go now? :smile:

**Comment by thealphadollar** [comment]
@tapaswenipathak Sorry for the misunderstanding; I've reverted my PR adding SoI. 

Is the Pull Request good to go now? :smile:

**Pull request merged**
