### PR TITLE
Add a timeline column

### PR DESCRIPTION
**Pull request by mridubhatnagar**
Fix <https://github.com/tapaswenipathak/Open-Source-Internships/issues/72>

### CODE REVIEW

**Comment by mridubhatnagar** [comment]
Sure. What text we would be having in the column?

**Comment by tapaswenipathak** [comment]
Timeline.

**Comment by mridubhatnagar** [comment]
So directly I should just put the links under the timeline column? We won't be hyperlinking.

**Comment by tapaswenipathak** [comment]
What do you think would be useful for the user?

**Comment by mridubhatnagar** [comment]
If I think in terms of a end user. I think clicking on the months and then getting redirected to the timeline page of the SOC program would be better. 

If we plan to put the links directly I think the interface would not look cleaner.

**Comment by tapaswenipathak** [comment]
I think months/timeline can change, right? Who would maintain? Think more, let me know how the table should be from a user perspective. Then pulling the information in creating a website, scaling, I wrote few tickets.

That's the thing with user's behavior/usability, the things user's do keep it in can't ignore state.

**Comment by prondubuisi** [comment]
@mridubhatnagar @tapaswenipathak I noticed that some of these internships don't have a separate timeline page url. Personally I would like to see when the applications open, this will help candidates prepare as against the timeline

**Comment by prondubuisi** [comment]
I think application opens field will be of better use than timeline

**Comment by mridubhatnagar** [comment]
> I think application opens field will be of better use than timeline

Hi @prondubuisi. Yes, from an end users perspective having application opens field would be better. But, going with that approach would have the following drawbacks.

1. The time when the application opens is not fixed. Each year dates, months could vary. Hence, it would be difficult to keep a track of it and maintain.

2. From all the mentioned internships. At the moment not every internship is having a 
pre-defined timeline at the moment.

**Comment by prondubuisi** [comment]
Okay let's see. Good work

**Pull request merged**
