### PR TITLE
Add theme file

### PR DESCRIPTION
**Pull request by prondubuisi**
fix issue #112
rename vendor file to vend to prevent heroku 403 error
https://opensourceinternship.herokuapp.com/
@tapaswenipathak I would love to remove all the unused dependencies if that is okay

### CODE REVIEW

**Comment by tapaswenipathak** [comment]
Please remove the unused dependencies.

**Comment by prondubuisi** [comment]
> Please remove the unused dependencies, lot of junk I see. I did few changes in the theme, can you pull the latest master branch? Nice work!

The only dependency I am currently using is the bootstrapp CSS, maybe I would have to use the updated theme for other internship projects. I will pull in your changes though to see what's new! If this is okay by you. I will just make the changes.

**Comment by tapaswenipathak** [comment]
Sure, go for it!

**Comment by prondubuisi** [comment]
Hello @tapaswenipathak I am done with the clean up, can you review?

**Comment by prondubuisi** [comment]
okay @tapaswenipathak  I am looking forward to the chat

**Comment by tapaswenipathak** [comment]
Please book a slot using https://calendly.com/tapaswenipathak.

**Comment by prondubuisi** [comment]
@tapaswenipathak can you confirm that I have booked a slot, I was expecting a notification from calendly

**Comment by tapaswenipathak** [comment]
Yes I have the invite in my calendar.

**Pull request closed without merging**
