### PR TITLE
Addition of SOC program

### PR DESCRIPTION
**Pull request by mridubhatnagar**

### CODE REVIEW

**Comment by mridubhatnagar** [comment]
As a part of https://github.com/tapaswenipathak/Internship at least 9 tickets to be closed. Have raised the PR for the very first one mentioned in the list.

**Comment by prondubuisi** [comment]
Hello @mridubhatnagar good work, I think this already exists under open source competitions

**Comment by tapaswenipathak** [comment]
Oh right, closing.

**Comment by mridubhatnagar** [comment]
Sorry for this. Would work on next one and raise the PR as mentioned in the guidelines.

**Comment by prondubuisi** [comment]
No problems @mridubhatnagar, looking forward to your next PR

**Pull request closed without merging**
